DROP TABLE IF EXISTS effects CASCADE;
DROP TABLE IF EXISTS article_details CASCADE;
DROP TABLE IF EXISTS therapies CASCADE;
DROP TABLE IF EXISTS articles CASCADE;
DROP TABLE IF EXISTS citations CASCADE;

